Repository LoganTHarvell/Astral-Pathfinder, pull requests merged in 2018-03, with the labels that each got.

#27 updated collider component
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/ShipManager.cpp
  Astral Pathfinder/Game/ShipManager.hpp
  Astral Pathfinder/Models/Game Object/ColliderComponent.cpp
  Astral Pathfinder/Models/Game Object/ColliderComponent.hpp
  Astral Pathfinder/Models/Game Object/GameObject.cpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
Labels: enhancement

#31 [WIP] updated data structures
  Astral Pathfinder.xcodeproj/project.pbxproj
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/ShipManager.cpp
  Astral Pathfinder/Game/UIManager.cpp
  Astral Pathfinder/Models/Game Object/ColliderComponent.cpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
  Astral Pathfinder/UI/Map.cpp
  Astral Pathfinder/UI/Map.hpp
  Astral Pathfinder/UI/PlanetInfo.cpp
  Astral Pathfinder/UI/Slider.cpp
  Astral Pathfinder/UI/Slider.hpp
  Astral Pathfinder/UI/TextBox.cpp
  Astral Pathfinder/UI/TextBox.hpp
  Astral Pathfinder/UI/TextureManager.cpp
  Astral Pathfinder/UI/TextureManager.hpp
  Astral Pathfinder/main.cpp
Labels: bug fix, enhancement

#33 planet discovery
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/UIManager.cpp
  Astral Pathfinder/Game/UIManager.hpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
Labels: enhancement, new feature

#32 Update ui
  Astral Pathfinder.xcodeproj/project.pbxproj
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/UIManager.cpp
  Astral Pathfinder/Game/UIManager.hpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Astral Pathfinder/Models/Ship.hpp
  Astral Pathfinder/UI/PlanetInfo.cpp
  Astral Pathfinder/UI/PlanetInfo.hpp
  Astral Pathfinder/UI/ShipInfo.cpp
  Astral Pathfinder/UI/ShipInfo.hpp
  Astral Pathfinder/UI/Slider.cpp
  Astral Pathfinder/UI/Slider.hpp
  Astral Pathfinder/UI/TextBox.cpp
  Astral Pathfinder/UI/TextBox.hpp
  Documentation/UI Layout.txt
  Resources/Assets/base.png
  Resources/Assets/slider.png
Labels: UI, enhancement
