Repository LoganTHarvell/Astral-Pathfinder, pull requests merged in 2018-02, with the labels that each got.

#6 Update classes
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Astral Pathfinder/Models/PlanetManager.cpp
  Astral Pathfinder/Models/PlanetManager.hpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
  Astral Pathfinder/UI/Map.cpp
  Astral Pathfinder/UI/Map.hpp
Labels: enhancement

#14 updated MARK comments for organization
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/ShipManager.cpp
  Astral Pathfinder/Game/ShipManager.hpp
  Astral Pathfinder/Models/GameObject.cpp
  Astral Pathfinder/Models/GameObject.hpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
  Astral Pathfinder/UI/Map.cpp
  Astral Pathfinder/UI/Map.hpp
  Astral Pathfinder/UI/TextureManager.cpp
  Astral Pathfinder/UI/TextureManager.hpp
Labels: documentation

#17 Planet collision
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/ShipManager.hpp
  Astral Pathfinder/Models/GameObject.cpp
  Astral Pathfinder/Models/GameObject.hpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
  Astral Pathfinder/UI/Map.cpp
  Astral Pathfinder/UI/Map.hpp
Labels: feature

#16 Movement
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/ShipManager.cpp
  Astral Pathfinder/Game/ShipManager.hpp
  Astral Pathfinder/Models/GameObject.cpp
  Astral Pathfinder/Models/GameObject.hpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
  Astral Pathfinder/UI/Map.cpp
  Astral Pathfinder/UI/Map.hpp
  Astral Pathfinder/main.cpp
Labels: feature

#19 added click event for future use
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Resources/Assets/planet2.png
Labels: feature

#18 ship rotation
  Astral Pathfinder.xcodeproj/project.pbxproj
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
  Resources/Assets/gameScreen.png
  Resources/Assets/movingPlayerShip.png
  Resources/Assets/planet.png
  Resources/Assets/playerShip.png
  Resources/Assets/simpleSpaceship.png
Labels: enhancement

#20 Planet select
  Astral Pathfinder.xcodeproj/project.pbxproj
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/ShipManager.cpp
  Astral Pathfinder/Game/ShipManager.hpp
  Astral Pathfinder/Game/UIManager.cpp
  Astral Pathfinder/Game/UIManager.hpp
  Astral Pathfinder/Models/GameObject.cpp
  Astral Pathfinder/Models/GameObject.hpp
  Astral Pathfinder/Models/Planet.cpp
  Astral Pathfinder/Models/Planet.hpp
  Astral Pathfinder/Models/Ship.hpp
  Astral Pathfinder/UI/PlanetInfo.cpp
  Astral Pathfinder/UI/PlanetInfo.hpp
  Astral Pathfinder/UI/TextBox.cpp
  Astral Pathfinder/UI/TextBox.hpp
  Documentation/Screenshots/Screen Shot 2018-02-24 at 11.00.31 PM.png
  Resources/Assets/Arial.ttf
  Resources/Assets/planet2.png
Labels: UI, feature

#24 issue solutions: multi-event polling, gameState structure, keyboard state movement
  Astral Pathfinder/Game/Game.cpp
  Astral Pathfinder/Game/Game.hpp
  Astral Pathfinder/Game/PlanetManager.cpp
  Astral Pathfinder/Game/PlanetManager.hpp
  Astral Pathfinder/Game/ShipManager.cpp
  Astral Pathfinder/Game/ShipManager.hpp
  Astral Pathfinder/Game/UIManager.cpp
  Astral Pathfinder/Game/UIManager.hpp
  Astral Pathfinder/Models/GameObject.hpp
  Astral Pathfinder/Models/Ship.cpp
  Astral Pathfinder/Models/Ship.hpp
  Astral Pathfinder/UI/PlanetInfo.cpp
  Astral Pathfinder/UI/PlanetInfo.hpp
  Astral Pathfinder/UI/TextBox.cpp
  Astral Pathfinder/UI/TextBox.hpp
Labels: enhancement
